"""add offer cost breakdown fields

Revision ID: 0f346a1591c2
Revises: 
Create Date: 2026-04-01 01:24:03.724771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f346a1591c2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('tuition', sa.Integer(), nullable=True))
    op.add_column('offers', sa.Column('room_and_board', sa.Integer(), nullable=True))
    op.add_column('offers', sa.Column('books_supplies', sa.Integer(), nullable=True))
    op.add_column('offers', sa.Column('personal_expenses', sa.Integer(), nullable=True))
    op.add_column('offers', sa.Column('transportation', sa.Integer(), nullable=True))
    op.add_column('offers', sa.Column('work_study', sa.Integer(), server_default='0', nullable=False))
    op.add_column('offers', sa.Column('total_cost', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'total_cost')
    op.drop_column('offers', 'work_study')
    op.drop_column('offers', 'transportation')
    op.drop_column('offers', 'personal_expenses')
    op.drop_column('offers', 'books_supplies')
    op.drop_column('offers', 'room_and_board')
    op.drop_column('offers', 'tuition')
    # ### end Alembic commands ###
