"""Global cleanup for noisy auto-created public admission schools."""

from __future__ import annotations

import argparse
import asyncio
import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from uuid import uuid4

from sqlalchemy import String, and_, cast, delete, func, or_, select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession

from scholarpath.db.models import (
    AdmissionEvent,
    CanonicalFact,
    CareerOutcomeProxy,
    CausalFeatureSnapshot,
    CausalOutcomeEvent,
    CausalShadowComparison,
    CausalTrendSignal,
    Conflict,
    DataPoint,
    DocumentChunk,
    EvidenceArtifact,
    FactQuarantine,
    FactLineage,
    GoNoGoReport,
    Institution,
    Offer,
    PolicyFact,
    PolicyFactAudit,
    Program,
    RawDocument,
    School,
    SchoolEvaluation,
    SchoolExternalId,
    SchoolMetricsYear,
    SourceEntityMap,
    Student,
)
from scholarpath.db.session import async_session_factory
from scholarpath.scripts.admission_truth_public_reddit import _is_noisy_autocreated_school_name
from scholarpath.scripts.admission_truth_public_shared import estimate_eligible_snapshots

_GENERIC_PLACEHOLDER_NAMES = {
    "a school",
    "school",
    "college",
    "top schools",
    "every top school",
    "every t20",
    "one ivy",
    "waiting on",
}

_ENHANCED_SAFE_EXACT_NAMES = {
    "the new school",
}

_GENERIC_FIRST_WORDS = {"top", "every", "one", "any", "all", "my", "your", "their", "our"}

_GENERIC_TOKEN_PATTERN = re.compile(
    r"\b(every|top|one|any|all|some|most|many|few|several|waiting|parents?|school|schools|ivy|t20|t50|college|colleges|hs)\b",
    re.I,
)

_INSTITUTION_KEYWORD_PATTERN = re.compile(
    r"\b(university|college|institute|polytechnic|state|tech|academy|school of)\b",
    re.I,
)


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Cleanup noisy auto-created placeholder schools from public admission sources.",
    )
    parser.add_argument("--run-id", default="", help="Optional run id; autogenerated when empty.")
    parser.add_argument(
        "--output-dir",
        default=".benchmarks/admission_truth_public",
        help="Directory for cleanup report artifacts.",
    )
    parser.add_argument(
        "--lookback-days",
        type=int,
        default=540,
        help="Lookback used for eligible snapshot estimates (default: 540).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Preview deletions and report matched schools without committing changes.",
    )
    parser.add_argument(
        "--enhanced-rules",
        action="store_true",
        help="Enable enhanced noisy placeholder detection for generic school phrases.",
    )
    return parser


async def _count_core_tables(session: AsyncSession) -> dict[str, int]:
    return {
        "students": int((await session.scalar(select(func.count()).select_from(Student))) or 0),
        "schools": int((await session.scalar(select(func.count()).select_from(School))) or 0),
        "admission_events": int((await session.scalar(select(func.count()).select_from(AdmissionEvent))) or 0),
        "causal_outcome_events": int((await session.scalar(select(func.count()).select_from(CausalOutcomeEvent))) or 0),
        "causal_feature_snapshots": int((await session.scalar(select(func.count()).select_from(CausalFeatureSnapshot))) or 0),
    }


async def _execute_delete_count(session: AsyncSession, statement: Any) -> int:
    result = await session.execute(statement)
    return max(0, int(result.rowcount or 0))


async def _has_protected_mapping(session: AsyncSession, *, school_id: Any) -> bool:
    ext_count = int(
        (
            await session.scalar(
                select(func.count()).select_from(SchoolExternalId).where(SchoolExternalId.school_id == school_id)
            )
        )
        or 0
    )
    map_count = int(
        (
            await session.scalar(
                select(func.count()).select_from(SourceEntityMap).where(
                    and_(
                        SourceEntityMap.school_id == school_id,
                        SourceEntityMap.external_id.is_not(None),
                    )
                )
            )
        )
        or 0
    )
    return ext_count > 0 or map_count > 0


def _match_enhanced_noisy_reason(value: str) -> str | None:
    name = str(value or "").strip()
    normalized = re.sub(r"\s+", " ", name.lower()).strip()
    if not normalized:
        return "empty_name"
    if normalized in _ENHANCED_SAFE_EXACT_NAMES:
        return None
    if normalized in _GENERIC_PLACEHOLDER_NAMES:
        return "generic_exact_phrase"
    if (
        _GENERIC_TOKEN_PATTERN.search(normalized)
        and not _INSTITUTION_KEYWORD_PATTERN.search(normalized)
    ):
        return "generic_tokens_without_institution_keyword"
    words = normalized.split()
    if words and len(words) <= 3 and words[0] in _GENERIC_FIRST_WORDS:
        return "generic_short_phrase_prefix"
    return None


def _match_noisy_reason(value: str, *, enhanced_rules: bool) -> str | None:
    if _is_noisy_autocreated_school_name(value):
        return "base_noisy_rule"
    if enhanced_rules:
        return _match_enhanced_noisy_reason(value)
    return None


async def _cleanup(
    session: AsyncSession,
    *,
    run_id: str,
    enhanced_rules: bool,
    dry_run: bool,
) -> dict[str, Any]:
    school_rows = list((await session.execute(select(School.id, School.name, School.metadata_))).all())
    candidates: list[tuple[Any, str, dict[str, Any]]] = []
    noisy_rows: list[tuple[Any, str, dict[str, Any], str]] = []
    protected_school_samples: list[str] = []
    match_reason_counts: dict[str, int] = {}

    for row in school_rows:
        metadata = row.metadata_ if isinstance(row.metadata_, dict) else {}
        if str(metadata.get("note") or "").strip() != "autocreated_placeholder_school":
            continue
        school_name = str(row.name or "").strip()
        candidates.append((row.id, school_name, metadata))
        match_reason = _match_noisy_reason(school_name, enhanced_rules=enhanced_rules)
        if match_reason:
            noisy_rows.append((row.id, school_name, metadata, match_reason))
            match_reason_counts[match_reason] = int(match_reason_counts.get(match_reason, 0)) + 1

    planned_rows_by_table: dict[str, int] = {
        "admission_events": 0,
        "causal_outcome_events": 0,
        "causal_feature_snapshots": 0,
        "school_evaluations": 0,
        "go_no_go_reports": 0,
        "offers": 0,
        "causal_shadow_comparisons": 0,
        "causal_trend_signals": 0,
        "fact_quarantine": 0,
        "conflicts": 0,
        "data_points": 0,
        "career_outcome_proxies": 0,
        "programs": 0,
        "evidence_artifacts": 0,
        "policy_fact_audits": 0,
        "policy_facts": 0,
        "document_chunks": 0,
        "raw_documents": 0,
        "fact_lineage": 0,
        "canonical_facts": 0,
        "school_metrics_year": 0,
        "source_entity_maps": 0,
        "school_external_ids": 0,
        "institutions": 0,
        "schools": 0,
        "students": 0,
    }
    deleted_rows_by_table: dict[str, int] = {key: 0 for key in planned_rows_by_table}

    deleted_schools = 0
    deleted_events = 0
    deleted_outcomes = 0
    deleted_snapshots = 0
    blocked_schools: list[str] = []
    deleted_school_samples: list[str] = []
    deletable_school_count = 0
    deletable_school_samples: list[dict[str, str]] = []

    for school_id, school_name, _metadata, match_reason in noisy_rows:
        if await _has_protected_mapping(session, school_id=school_id):
            protected_school_samples.append(school_name)
            continue
        deletable_school_count += 1
        if len(deletable_school_samples) < 80:
            deletable_school_samples.append(
                {
                    "school_id": str(school_id),
                    "school_name": school_name,
                    "match_reason": match_reason,
                }
            )
        local_rows: dict[str, int] = {key: 0 for key in planned_rows_by_table}
        try:
            async with session.begin_nested():
                local_rows["school_evaluations"] = await _execute_delete_count(
                    session,
                    delete(SchoolEvaluation).where(SchoolEvaluation.school_id == school_id),
                )
                local_rows["causal_feature_snapshots"] = await _execute_delete_count(
                    session,
                    delete(CausalFeatureSnapshot).where(CausalFeatureSnapshot.school_id == school_id),
                )
                local_rows["causal_outcome_events"] = await _execute_delete_count(
                    session,
                    delete(CausalOutcomeEvent).where(CausalOutcomeEvent.school_id == school_id),
                )
                local_rows["admission_events"] = await _execute_delete_count(
                    session,
                    delete(AdmissionEvent).where(AdmissionEvent.school_id == school_id),
                )
                offer_ids = list(
                    (
                        await session.execute(
                            select(Offer.id).where(Offer.school_id == school_id),
                        )
                    )
                    .scalars()
                    .all()
                )
                if offer_ids:
                    local_rows["go_no_go_reports"] = await _execute_delete_count(
                        session,
                        delete(GoNoGoReport).where(GoNoGoReport.offer_id.in_(offer_ids)),
                    )
                local_rows["offers"] = await _execute_delete_count(
                    session,
                    delete(Offer).where(Offer.school_id == school_id),
                )
                local_rows["causal_shadow_comparisons"] = await _execute_delete_count(
                    session,
                    delete(CausalShadowComparison).where(
                        cast(CausalShadowComparison.school_id, String) == str(school_id)
                    ),
                )
                local_rows["causal_trend_signals"] = await _execute_delete_count(
                    session,
                    delete(CausalTrendSignal).where(CausalTrendSignal.school_id == school_id),
                )
                local_rows["fact_quarantine"] = await _execute_delete_count(
                    session,
                    delete(FactQuarantine).where(FactQuarantine.school_id == school_id),
                )
                local_rows["conflicts"] = await _execute_delete_count(
                    session,
                    delete(Conflict).where(Conflict.school_id == school_id),
                )
                local_rows["data_points"] = await _execute_delete_count(
                    session,
                    delete(DataPoint).where(DataPoint.school_id == school_id),
                )
                local_rows["career_outcome_proxies"] = await _execute_delete_count(
                    session,
                    delete(CareerOutcomeProxy).where(CareerOutcomeProxy.school_id == school_id),
                )
                local_rows["programs"] = await _execute_delete_count(
                    session,
                    delete(Program).where(Program.school_id == school_id),
                )
                local_rows["evidence_artifacts"] = await _execute_delete_count(
                    session,
                    delete(EvidenceArtifact).where(EvidenceArtifact.school_id == school_id),
                )

                canonical_ids = list(
                    (
                        await session.execute(
                            select(CanonicalFact.id).where(CanonicalFact.school_id == school_id),
                        )
                    )
                    .scalars()
                    .all()
                )
                if canonical_ids:
                    local_rows["fact_lineage"] = await _execute_delete_count(
                        session,
                        delete(FactLineage).where(FactLineage.canonical_fact_id.in_(canonical_ids)),
                    )
                local_rows["canonical_facts"] = await _execute_delete_count(
                    session,
                    delete(CanonicalFact).where(CanonicalFact.school_id == school_id),
                )

                raw_document_ids = list(
                    (
                        await session.execute(
                            select(RawDocument.id).where(RawDocument.school_id == school_id),
                        )
                    )
                    .scalars()
                    .all()
                )
                if raw_document_ids:
                    local_rows["document_chunks"] = await _execute_delete_count(
                        session,
                        delete(DocumentChunk).where(DocumentChunk.raw_document_id.in_(raw_document_ids)),
                    )
                local_rows["policy_fact_audits"] = await _execute_delete_count(
                    session,
                    delete(PolicyFactAudit).where(PolicyFactAudit.school_id == school_id),
                )
                local_rows["policy_facts"] = await _execute_delete_count(
                    session,
                    delete(PolicyFact).where(PolicyFact.school_id == school_id),
                )
                local_rows["raw_documents"] = await _execute_delete_count(
                    session,
                    delete(RawDocument).where(RawDocument.school_id == school_id),
                )

                local_rows["school_metrics_year"] = await _execute_delete_count(
                    session,
                    delete(SchoolMetricsYear).where(SchoolMetricsYear.school_id == school_id),
                )
                local_rows["source_entity_maps"] = await _execute_delete_count(
                    session,
                    delete(SourceEntityMap).where(SourceEntityMap.school_id == school_id),
                )
                local_rows["school_external_ids"] = await _execute_delete_count(
                    session,
                    delete(SchoolExternalId).where(SchoolExternalId.school_id == school_id),
                )
                local_rows["institutions"] = await _execute_delete_count(
                    session,
                    delete(Institution).where(Institution.school_id == school_id),
                )

                local_rows["schools"] = await _execute_delete_count(
                    session,
                    delete(School).where(School.id == school_id),
                )

                still_exists = int(
                    (
                        await session.scalar(
                            select(func.count()).select_from(School).where(School.id == school_id)
                        )
                    )
                    or 0
                )
                if still_exists > 0:
                    blocked_schools.append(school_name)
                    continue

                deleted_schools += 1
                deleted_events += int(local_rows["admission_events"])
                deleted_outcomes += int(local_rows["causal_outcome_events"])
                deleted_snapshots += int(local_rows["causal_feature_snapshots"])
                for key, value in local_rows.items():
                    deleted_rows_by_table[key] = int(deleted_rows_by_table.get(key, 0)) + int(value)
                if len(deleted_school_samples) < 100:
                    deleted_school_samples.append(school_name)
        except IntegrityError:
            blocked_schools.append(school_name)
        finally:
            for key, value in local_rows.items():
                planned_rows_by_table[key] = int(planned_rows_by_table.get(key, 0)) + int(value)

    orphan_student_ids = list(
        (
            await session.execute(
                select(Student.id).where(
                    or_(
                        Student.email.like("reddit_%@public-data.local"),
                        Student.email.like("cc_%@public-data.local"),
                    )
                ),
            )
        )
        .scalars()
        .all()
    )
    deleted_students = 0
    blocked_students = 0
    for student_id in orphan_student_ids:
        events_left = int(
            (
                await session.scalar(
                    select(func.count()).select_from(AdmissionEvent).where(AdmissionEvent.student_id == student_id)
                )
            )
            or 0
        )
        if events_left > 0:
            continue
        try:
            async with session.begin_nested():
                deleted_snapshots += await _execute_delete_count(
                    session,
                    delete(CausalFeatureSnapshot).where(CausalFeatureSnapshot.student_id == student_id),
                )
                deleted_outcomes += await _execute_delete_count(
                    session,
                    delete(CausalOutcomeEvent).where(CausalOutcomeEvent.student_id == student_id),
                )
                deleted_student_now = await _execute_delete_count(
                    session,
                    delete(Student).where(Student.id == student_id),
                )
                deleted_students += deleted_student_now
                deleted_rows_by_table["students"] = int(deleted_rows_by_table.get("students", 0)) + int(
                    deleted_student_now
                )
                planned_rows_by_table["students"] = int(planned_rows_by_table.get("students", 0)) + int(
                    deleted_student_now
                )
        except IntegrityError:
            blocked_students += 1
            continue

    if dry_run:
        await session.rollback()

    return {
        "run_id": run_id,
        "status": "ok",
        "dry_run": bool(dry_run),
        "enhanced_rules": bool(enhanced_rules),
        "schools_candidate": len(candidates),
        "schools_detected_noisy": len(noisy_rows),
        "schools_deletable": int(deletable_school_count),
        "schools_protected": len(protected_school_samples),
        "schools_deleted": deleted_schools,
        "schools_blocked": len(blocked_schools),
        "schools_protected_by_mapping": len(protected_school_samples),  # backward-compatible alias
        "blocked_school_samples": blocked_schools[:50],
        "protected_school_samples": protected_school_samples[:50],
        "deleted_school_samples": deleted_school_samples,
        "deletable_school_samples": deletable_school_samples,
        "match_reason_counts": match_reason_counts,
        "rows_to_delete_by_table": (planned_rows_by_table if dry_run else deleted_rows_by_table),
        "rows_planned_by_table": planned_rows_by_table,
        "rows_deleted_by_table": deleted_rows_by_table,
        "admission_events_deleted": deleted_events,
        "causal_outcomes_deleted": deleted_outcomes,
        "feature_snapshots_deleted": deleted_snapshots,
        "students_deleted": deleted_students,
        "students_blocked": blocked_students,
        "noisy_school_samples": [name for _, name, _, _ in noisy_rows[:100]],
    }


async def _run(args: argparse.Namespace) -> dict[str, Any]:
    run_id = args.run_id or f"admission-public-cleanup-{datetime.now(timezone.utc):%Y%m%d-%H%M%S}-{uuid4().hex[:6]}"
    output_root = Path(args.output_dir).expanduser().resolve() / run_id
    output_root.mkdir(parents=True, exist_ok=True)

    async with async_session_factory() as session:
        before_counts = await _count_core_tables(session)
        eligible_before = await estimate_eligible_snapshots(session, lookback_days=int(args.lookback_days))
        cleanup_result = await _cleanup(
            session,
            run_id=run_id,
            enhanced_rules=bool(args.enhanced_rules),
            dry_run=bool(args.dry_run),
        )
        if not args.dry_run:
            await session.commit()
        after_counts = await _count_core_tables(session)
        eligible_after = await estimate_eligible_snapshots(session, lookback_days=int(args.lookback_days))

    payload = {
        "status": "ok",
        "run_id": run_id,
        "request": {
            "lookback_days": int(args.lookback_days),
            "output_dir": str(output_root.parent),
            "dry_run": bool(args.dry_run),
            "enhanced_rules": bool(args.enhanced_rules),
        },
        "counts": {
            "before": before_counts,
            "after": after_counts,
            "delta": {
                key: int(after_counts.get(key, 0)) - int(before_counts.get(key, 0))
                for key in sorted(set(before_counts) | set(after_counts))
            },
        },
        "eligible_snapshots_540": {
            "before": int(eligible_before),
            "after": int(eligible_after),
            "delta": int(eligible_after) - int(eligible_before),
        },
        "cleanup": cleanup_result,
    }

    report_json = output_root / "admission_truth_public_cleanup_report.json"
    report_md = output_root / "admission_truth_public_cleanup_report.md"
    report_json.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")

    md_lines = [
        f"# Public Cleanup `{run_id}`",
        "",
        f"- dry_run: `{bool(args.dry_run)}`",
        f"- enhanced_rules: `{bool(args.enhanced_rules)}`",
        f"- schools_candidate: `{cleanup_result.get('schools_candidate')}`",
        f"- schools_deletable: `{cleanup_result.get('schools_deletable')}`",
        f"- schools_protected: `{cleanup_result.get('schools_protected')}`",
        f"- schools_deleted: `{cleanup_result.get('schools_deleted')}`",
        f"- schools_protected_by_mapping: `{cleanup_result.get('schools_protected_by_mapping')}`",
        f"- admission_events_deleted: `{cleanup_result.get('admission_events_deleted')}`",
        f"- outcomes_deleted: `{cleanup_result.get('causal_outcomes_deleted')}`",
        f"- snapshots_deleted: `{cleanup_result.get('feature_snapshots_deleted')}`",
        f"- students_deleted: `{cleanup_result.get('students_deleted')}`",
        f"- eligible_delta: `{int(eligible_after) - int(eligible_before)}`",
    ]
    report_md.write_text("\n".join(md_lines), encoding="utf-8")

    payload["report_json"] = str(report_json)
    payload["report_md"] = str(report_md)
    print(json.dumps(payload, ensure_ascii=False, indent=2))
    return payload


def main() -> None:
    parser = _build_parser()
    args = parser.parse_args()
    asyncio.run(_run(args))


if __name__ == "__main__":
    main()
