"""Add missing schools to ScholarPath database (US News ~top 100 + QS notable + top LACs)."""

import asyncio
import asyncpg

DB_DSN = "postgresql://scholarpath:scholarpath@localhost:5432/scholarpath"

NEW_SCHOOLS = [
    # --- US News ~50-100 National Universities ---
    {"name": "Georgia Institute of Technology", "name_cn": "佐治亚理工学院", "city": "Atlanta", "state": "GA", "school_type": "technical", "size_category": "large", "us_news_rank": 33, "acceptance_rate": 0.17, "sat_25": 1370, "sat_75": 1530, "tuition_oos": 33794, "avg_net_price": 18418, "intl_student_pct": 0.13, "student_faculty_ratio": 15.0, "graduation_rate_4yr": 0.44, "campus_setting": "urban", "website_url": "https://www.gatech.edu"},
    {"name": "University of Illinois Urbana-Champaign", "name_cn": "伊利诺伊大学厄巴纳-香槟分校", "city": "Champaign", "state": "IL", "school_type": "university", "size_category": "large", "us_news_rank": 35, "acceptance_rate": 0.45, "sat_25": 1310, "sat_75": 1510, "tuition_oos": 34316, "avg_net_price": 18735, "intl_student_pct": 0.16, "student_faculty_ratio": 20.0, "graduation_rate_4yr": 0.72, "campus_setting": "urban", "website_url": "https://illinois.edu"},
    {"name": "University of Wisconsin-Madison", "name_cn": "威斯康星大学麦迪逊分校", "city": "Madison", "state": "WI", "school_type": "university", "size_category": "large", "us_news_rank": 35, "acceptance_rate": 0.49, "sat_25": 1300, "sat_75": 1480, "tuition_oos": 39427, "avg_net_price": 17106, "intl_student_pct": 0.12, "student_faculty_ratio": 17.0, "graduation_rate_4yr": 0.64, "campus_setting": "urban", "website_url": "https://www.wisc.edu"},
    {"name": "University of California, Santa Barbara", "name_cn": "加州大学圣塔芭芭拉分校", "city": "Santa Barbara", "state": "CA", "school_type": "university", "size_category": "large", "us_news_rank": 35, "acceptance_rate": 0.26, "sat_25": 1250, "sat_75": 1470, "tuition_oos": 44196, "avg_net_price": 17400, "intl_student_pct": 0.11, "student_faculty_ratio": 18.0, "graduation_rate_4yr": 0.67, "campus_setting": "suburban", "website_url": "https://www.ucsb.edu"},
    {"name": "Purdue University", "name_cn": "普渡大学", "city": "West Lafayette", "state": "IN", "school_type": "university", "size_category": "large", "us_news_rank": 43, "acceptance_rate": 0.53, "sat_25": 1200, "sat_75": 1440, "tuition_oos": 28794, "avg_net_price": 15736, "intl_student_pct": 0.14, "student_faculty_ratio": 13.0, "graduation_rate_4yr": 0.55, "campus_setting": "suburban", "website_url": "https://www.purdue.edu"},
    {"name": "Lehigh University", "name_cn": "理海大学", "city": "Bethlehem", "state": "PA", "school_type": "university", "size_category": "medium", "us_news_rank": 46, "acceptance_rate": 0.32, "sat_25": 1310, "sat_75": 1470, "tuition_oos": 60590, "avg_net_price": 33200, "intl_student_pct": 0.10, "student_faculty_ratio": 10.0, "graduation_rate_4yr": 0.78, "campus_setting": "suburban", "website_url": "https://www1.lehigh.edu"},
    {"name": "Northeastern University", "name_cn": "东北大学", "city": "Boston", "state": "MA", "school_type": "university", "size_category": "large", "us_news_rank": 53, "acceptance_rate": 0.07, "sat_25": 1410, "sat_75": 1540, "tuition_oos": 60192, "avg_net_price": 33800, "intl_student_pct": 0.20, "student_faculty_ratio": 14.0, "graduation_rate_4yr": 0.79, "campus_setting": "urban", "website_url": "https://www.northeastern.edu"},
    {"name": "University of Rochester", "name_cn": "罗切斯特大学", "city": "Rochester", "state": "NY", "school_type": "university", "size_category": "medium", "us_news_rank": 47, "acceptance_rate": 0.37, "sat_25": 1330, "sat_75": 1500, "tuition_oos": 61678, "avg_net_price": 33600, "intl_student_pct": 0.21, "student_faculty_ratio": 10.0, "graduation_rate_4yr": 0.77, "campus_setting": "suburban", "website_url": "https://www.rochester.edu"},
    {"name": "Case Western Reserve University", "name_cn": "凯斯西储大学", "city": "Cleveland", "state": "OH", "school_type": "university", "size_category": "medium", "us_news_rank": 53, "acceptance_rate": 0.30, "sat_25": 1350, "sat_75": 1510, "tuition_oos": 57750, "avg_net_price": 35200, "intl_student_pct": 0.16, "student_faculty_ratio": 11.0, "graduation_rate_4yr": 0.73, "campus_setting": "urban", "website_url": "https://case.edu"},
    {"name": "Tulane University", "name_cn": "杜兰大学", "city": "New Orleans", "state": "LA", "school_type": "university", "size_category": "medium", "us_news_rank": 73, "acceptance_rate": 0.11, "sat_25": 1320, "sat_75": 1480, "tuition_oos": 62844, "avg_net_price": 38700, "intl_student_pct": 0.08, "student_faculty_ratio": 8.0, "graduation_rate_4yr": 0.74, "campus_setting": "urban", "website_url": "https://tulane.edu"},
    {"name": "Brandeis University", "name_cn": "布兰迪斯大学", "city": "Waltham", "state": "MA", "school_type": "university", "size_category": "small", "us_news_rank": 60, "acceptance_rate": 0.33, "sat_25": 1310, "sat_75": 1480, "tuition_oos": 62070, "avg_net_price": 34500, "intl_student_pct": 0.20, "student_faculty_ratio": 10.0, "graduation_rate_4yr": 0.82, "campus_setting": "suburban", "website_url": "https://www.brandeis.edu"},
    {"name": "Wake Forest University", "name_cn": "维克森林大学", "city": "Winston-Salem", "state": "NC", "school_type": "university", "size_category": "medium", "us_news_rank": 47, "acceptance_rate": 0.22, "sat_25": 1340, "sat_75": 1490, "tuition_oos": 61048, "avg_net_price": 34000, "intl_student_pct": 0.08, "student_faculty_ratio": 10.0, "graduation_rate_4yr": 0.82, "campus_setting": "suburban", "website_url": "https://www.wfu.edu"},
    {"name": "Villanova University", "name_cn": "维拉诺瓦大学", "city": "Villanova", "state": "PA", "school_type": "university", "size_category": "medium", "us_news_rank": 67, "acceptance_rate": 0.23, "sat_25": 1340, "sat_75": 1490, "tuition_oos": 60696, "avg_net_price": 37000, "intl_student_pct": 0.04, "student_faculty_ratio": 11.0, "graduation_rate_4yr": 0.84, "campus_setting": "suburban", "website_url": "https://www1.villanova.edu"},
    {"name": "Rensselaer Polytechnic Institute", "name_cn": "伦斯勒理工学院", "city": "Troy", "state": "NY", "school_type": "technical", "size_category": "medium", "us_news_rank": 60, "acceptance_rate": 0.57, "sat_25": 1330, "sat_75": 1500, "tuition_oos": 60124, "avg_net_price": 38500, "intl_student_pct": 0.10, "student_faculty_ratio": 13.0, "graduation_rate_4yr": 0.65, "campus_setting": "urban", "website_url": "https://www.rpi.edu"},
    {"name": "Worcester Polytechnic Institute", "name_cn": "伍斯特理工学院", "city": "Worcester", "state": "MA", "school_type": "technical", "size_category": "medium", "us_news_rank": 67, "acceptance_rate": 0.49, "sat_25": 1310, "sat_75": 1470, "tuition_oos": 57536, "avg_net_price": 35400, "intl_student_pct": 0.14, "student_faculty_ratio": 13.0, "graduation_rate_4yr": 0.67, "campus_setting": "urban", "website_url": "https://www.wpi.edu"},
    {"name": "University of Miami", "name_cn": "迈阿密大学", "city": "Coral Gables", "state": "FL", "school_type": "university", "size_category": "large", "us_news_rank": 67, "acceptance_rate": 0.19, "sat_25": 1310, "sat_75": 1470, "tuition_oos": 57194, "avg_net_price": 34500, "intl_student_pct": 0.13, "student_faculty_ratio": 12.0, "graduation_rate_4yr": 0.74, "campus_setting": "suburban", "website_url": "https://welcome.miami.edu"},
    {"name": "Southern Methodist University", "name_cn": "南卫理公会大学", "city": "Dallas", "state": "TX", "school_type": "university", "size_category": "medium", "us_news_rank": 67, "acceptance_rate": 0.49, "sat_25": 1280, "sat_75": 1450, "tuition_oos": 60942, "avg_net_price": 38200, "intl_student_pct": 0.09, "student_faculty_ratio": 11.0, "graduation_rate_4yr": 0.72, "campus_setting": "urban", "website_url": "https://www.smu.edu"},
    {"name": "Pepperdine University", "name_cn": "佩伯代因大学", "city": "Malibu", "state": "CA", "school_type": "university", "size_category": "small", "us_news_rank": 76, "acceptance_rate": 0.31, "sat_25": 1260, "sat_75": 1430, "tuition_oos": 62192, "avg_net_price": 39800, "intl_student_pct": 0.10, "student_faculty_ratio": 13.0, "graduation_rate_4yr": 0.77, "campus_setting": "suburban", "website_url": "https://www.pepperdine.edu"},
    {"name": "Penn State University Park", "name_cn": "宾夕法尼亚州立大学", "city": "University Park", "state": "PA", "school_type": "university", "size_category": "large", "us_news_rank": 60, "acceptance_rate": 0.54, "sat_25": 1200, "sat_75": 1390, "tuition_oos": 38824, "avg_net_price": 21700, "intl_student_pct": 0.11, "student_faculty_ratio": 15.0, "graduation_rate_4yr": 0.65, "campus_setting": "suburban", "website_url": "https://www.psu.edu"},
    {"name": "University of Pittsburgh", "name_cn": "匹兹堡大学", "city": "Pittsburgh", "state": "PA", "school_type": "university", "size_category": "large", "us_news_rank": 67, "acceptance_rate": 0.42, "sat_25": 1280, "sat_75": 1460, "tuition_oos": 35742, "avg_net_price": 21500, "intl_student_pct": 0.08, "student_faculty_ratio": 14.0, "graduation_rate_4yr": 0.68, "campus_setting": "urban", "website_url": "https://www.pitt.edu"},
    {"name": "University of Connecticut", "name_cn": "康涅狄格大学", "city": "Storrs", "state": "CT", "school_type": "university", "size_category": "large", "us_news_rank": 58, "acceptance_rate": 0.56, "sat_25": 1250, "sat_75": 1420, "tuition_oos": 40798, "avg_net_price": 21200, "intl_student_pct": 0.06, "student_faculty_ratio": 16.0, "graduation_rate_4yr": 0.70, "campus_setting": "rural", "website_url": "https://uconn.edu"},
    {"name": "University of California, Santa Cruz", "name_cn": "加州大学圣克鲁兹分校", "city": "Santa Cruz", "state": "CA", "school_type": "university", "size_category": "large", "us_news_rank": 82, "acceptance_rate": 0.47, "sat_25": 1140, "sat_75": 1370, "tuition_oos": 43830, "avg_net_price": 18600, "intl_student_pct": 0.09, "student_faculty_ratio": 25.0, "graduation_rate_4yr": 0.57, "campus_setting": "suburban", "website_url": "https://www.ucsc.edu"},
    {"name": "University of Iowa", "name_cn": "爱荷华大学", "city": "Iowa City", "state": "IA", "school_type": "university", "size_category": "large", "us_news_rank": 82, "acceptance_rate": 0.84, "sat_25": 1100, "sat_75": 1320, "tuition_oos": 31568, "avg_net_price": 17800, "intl_student_pct": 0.09, "student_faculty_ratio": 15.0, "graduation_rate_4yr": 0.54, "campus_setting": "urban", "website_url": "https://uiowa.edu"},
    {"name": "Stony Brook University", "name_cn": "石溪大学", "city": "Stony Brook", "state": "NY", "school_type": "university", "size_category": "large", "us_news_rank": 58, "acceptance_rate": 0.49, "sat_25": 1280, "sat_75": 1450, "tuition_oos": 29920, "avg_net_price": 15200, "intl_student_pct": 0.15, "student_faculty_ratio": 19.0, "graduation_rate_4yr": 0.55, "campus_setting": "suburban", "website_url": "https://www.stonybrook.edu"},
    {"name": "University at Buffalo", "name_cn": "布法罗大学", "city": "Buffalo", "state": "NY", "school_type": "university", "size_category": "large", "us_news_rank": 89, "acceptance_rate": 0.66, "sat_25": 1170, "sat_75": 1360, "tuition_oos": 29400, "avg_net_price": 17600, "intl_student_pct": 0.14, "student_faculty_ratio": 14.0, "graduation_rate_4yr": 0.56, "campus_setting": "suburban", "website_url": "https://www.buffalo.edu"},
    {"name": "University of Georgia", "name_cn": "佐治亚大学", "city": "Athens", "state": "GA", "school_type": "university", "size_category": "large", "us_news_rank": 47, "acceptance_rate": 0.43, "sat_25": 1250, "sat_75": 1420, "tuition_oos": 31120, "avg_net_price": 17500, "intl_student_pct": 0.05, "student_faculty_ratio": 17.0, "graduation_rate_4yr": 0.68, "campus_setting": "urban", "website_url": "https://www.uga.edu"},
    {"name": "Florida State University", "name_cn": "佛罗里达州立大学", "city": "Tallahassee", "state": "FL", "school_type": "university", "size_category": "large", "us_news_rank": 53, "acceptance_rate": 0.25, "sat_25": 1230, "sat_75": 1380, "tuition_oos": 21683, "avg_net_price": 14700, "intl_student_pct": 0.04, "student_faculty_ratio": 21.0, "graduation_rate_4yr": 0.68, "campus_setting": "urban", "website_url": "https://www.fsu.edu"},
    {"name": "University of California, Riverside", "name_cn": "加州大学河滨分校", "city": "Riverside", "state": "CA", "school_type": "university", "size_category": "large", "us_news_rank": 76, "acceptance_rate": 0.56, "sat_25": 1100, "sat_75": 1320, "tuition_oos": 43236, "avg_net_price": 14900, "intl_student_pct": 0.10, "student_faculty_ratio": 22.0, "graduation_rate_4yr": 0.52, "campus_setting": "urban", "website_url": "https://www.ucr.edu"},
    {"name": "Clemson University", "name_cn": "克莱姆森大学", "city": "Clemson", "state": "SC", "school_type": "university", "size_category": "large", "us_news_rank": 82, "acceptance_rate": 0.43, "sat_25": 1220, "sat_75": 1390, "tuition_oos": 39498, "avg_net_price": 21400, "intl_student_pct": 0.03, "student_faculty_ratio": 16.0, "graduation_rate_4yr": 0.60, "campus_setting": "rural", "website_url": "https://www.clemson.edu"},
    {"name": "Texas A&M University", "name_cn": "德克萨斯农工大学", "city": "College Station", "state": "TX", "school_type": "university", "size_category": "large", "us_news_rank": 43, "acceptance_rate": 0.63, "sat_25": 1160, "sat_75": 1380, "tuition_oos": 39394, "avg_net_price": 19200, "intl_student_pct": 0.06, "student_faculty_ratio": 19.0, "graduation_rate_4yr": 0.56, "campus_setting": "suburban", "website_url": "https://www.tamu.edu"},
    {"name": "George Washington University", "name_cn": "乔治华盛顿大学", "city": "Washington", "state": "DC", "school_type": "university", "size_category": "medium", "us_news_rank": 67, "acceptance_rate": 0.49, "sat_25": 1300, "sat_75": 1460, "tuition_oos": 62410, "avg_net_price": 38400, "intl_student_pct": 0.11, "student_faculty_ratio": 12.0, "graduation_rate_4yr": 0.77, "campus_setting": "urban", "website_url": "https://www.gwu.edu"},
    {"name": "Syracuse University", "name_cn": "雪城大学", "city": "Syracuse", "state": "NY", "school_type": "university", "size_category": "large", "us_news_rank": 67, "acceptance_rate": 0.41, "sat_25": 1200, "sat_75": 1380, "tuition_oos": 57750, "avg_net_price": 34600, "intl_student_pct": 0.12, "student_faculty_ratio": 15.0, "graduation_rate_4yr": 0.70, "campus_setting": "urban", "website_url": "https://www.syracuse.edu"},
    {"name": "University of Denver", "name_cn": "丹佛大学", "city": "Denver", "state": "CO", "school_type": "university", "size_category": "medium", "us_news_rank": 89, "acceptance_rate": 0.58, "sat_25": 1180, "sat_75": 1370, "tuition_oos": 55980, "avg_net_price": 33200, "intl_student_pct": 0.09, "student_faculty_ratio": 11.0, "graduation_rate_4yr": 0.69, "campus_setting": "urban", "website_url": "https://www.du.edu"},
    {"name": "Santa Clara University", "name_cn": "圣塔克拉拉大学", "city": "Santa Clara", "state": "CA", "school_type": "university", "size_category": "medium", "us_news_rank": 60, "acceptance_rate": 0.49, "sat_25": 1310, "sat_75": 1460, "tuition_oos": 57234, "avg_net_price": 36500, "intl_student_pct": 0.07, "student_faculty_ratio": 11.0, "graduation_rate_4yr": 0.83, "campus_setting": "urban", "website_url": "https://www.scu.edu"},
    {"name": "Fordham University", "name_cn": "福特汉姆大学", "city": "New York", "state": "NY", "school_type": "university", "size_category": "medium", "us_news_rank": 82, "acceptance_rate": 0.46, "sat_25": 1260, "sat_75": 1420, "tuition_oos": 58082, "avg_net_price": 36200, "intl_student_pct": 0.08, "student_faculty_ratio": 14.0, "graduation_rate_4yr": 0.77, "campus_setting": "urban", "website_url": "https://www.fordham.edu"},
    {"name": "University of Delaware", "name_cn": "特拉华大学", "city": "Newark", "state": "DE", "school_type": "university", "size_category": "large", "us_news_rank": 89, "acceptance_rate": 0.68, "sat_25": 1150, "sat_75": 1340, "tuition_oos": 36700, "avg_net_price": 20800, "intl_student_pct": 0.06, "student_faculty_ratio": 14.0, "graduation_rate_4yr": 0.63, "campus_setting": "suburban", "website_url": "https://www.udel.edu"},
    {"name": "Colorado School of Mines", "name_cn": "科罗拉多矿业大学", "city": "Golden", "state": "CO", "school_type": "technical", "size_category": "medium", "us_news_rank": 67, "acceptance_rate": 0.54, "sat_25": 1280, "sat_75": 1450, "tuition_oos": 42030, "avg_net_price": 26500, "intl_student_pct": 0.08, "student_faculty_ratio": 16.0, "graduation_rate_4yr": 0.52, "campus_setting": "suburban", "website_url": "https://www.mines.edu"},
    {"name": "Yeshiva University", "name_cn": "叶史瓦大学", "city": "New York", "state": "NY", "school_type": "university", "size_category": "small", "us_news_rank": 67, "acceptance_rate": 0.53, "sat_25": 1220, "sat_75": 1430, "tuition_oos": 48620, "avg_net_price": 23500, "intl_student_pct": 0.18, "student_faculty_ratio": 7.0, "graduation_rate_4yr": 0.66, "campus_setting": "urban", "website_url": "https://www.yu.edu"},
    {"name": "Loyola Marymount University", "name_cn": "洛约拉马利蒙特大学", "city": "Los Angeles", "state": "CA", "school_type": "university", "size_category": "medium", "us_news_rank": 76, "acceptance_rate": 0.42, "sat_25": 1220, "sat_75": 1380, "tuition_oos": 55546, "avg_net_price": 36000, "intl_student_pct": 0.07, "student_faculty_ratio": 10.0, "graduation_rate_4yr": 0.75, "campus_setting": "urban", "website_url": "https://www.lmu.edu"},
    {"name": "University of Tennessee, Knoxville", "name_cn": "田纳西大学诺克斯维尔分校", "city": "Knoxville", "state": "TN", "school_type": "university", "size_category": "large", "us_news_rank": 98, "acceptance_rate": 0.70, "sat_25": 1120, "sat_75": 1310, "tuition_oos": 31664, "avg_net_price": 18500, "intl_student_pct": 0.04, "student_faculty_ratio": 17.0, "graduation_rate_4yr": 0.52, "campus_setting": "urban", "website_url": "https://www.utk.edu"},
    {"name": "University of Kansas", "name_cn": "堪萨斯大学", "city": "Lawrence", "state": "KS", "school_type": "university", "size_category": "large", "us_news_rank": 98, "acceptance_rate": 0.88, "sat_25": 1070, "sat_75": 1310, "tuition_oos": 28000, "avg_net_price": 17800, "intl_student_pct": 0.07, "student_faculty_ratio": 16.0, "graduation_rate_4yr": 0.45, "campus_setting": "suburban", "website_url": "https://www.ku.edu"},
    {"name": "Baylor University", "name_cn": "贝勒大学", "city": "Waco", "state": "TX", "school_type": "university", "size_category": "large", "us_news_rank": 93, "acceptance_rate": 0.53, "sat_25": 1200, "sat_75": 1370, "tuition_oos": 52262, "avg_net_price": 31500, "intl_student_pct": 0.05, "student_faculty_ratio": 15.0, "graduation_rate_4yr": 0.64, "campus_setting": "urban", "website_url": "https://www.baylor.edu"},
    {"name": "Gonzaga University", "name_cn": "贡萨格大学", "city": "Spokane", "state": "WA", "school_type": "university", "size_category": "medium", "us_news_rank": 93, "acceptance_rate": 0.62, "sat_25": 1180, "sat_75": 1360, "tuition_oos": 50470, "avg_net_price": 32600, "intl_student_pct": 0.03, "student_faculty_ratio": 11.0, "graduation_rate_4yr": 0.77, "campus_setting": "urban", "website_url": "https://www.gonzaga.edu"},
    {"name": "Marquette University", "name_cn": "马凯特大学", "city": "Milwaukee", "state": "WI", "school_type": "university", "size_category": "medium", "us_news_rank": 89, "acceptance_rate": 0.72, "sat_25": 1130, "sat_75": 1310, "tuition_oos": 47290, "avg_net_price": 29500, "intl_student_pct": 0.04, "student_faculty_ratio": 14.0, "graduation_rate_4yr": 0.65, "campus_setting": "urban", "website_url": "https://www.marquette.edu"},

    # --- Top Liberal Arts Colleges ---
    {"name": "Swarthmore College", "name_cn": "斯沃斯莫尔学院", "city": "Swarthmore", "state": "PA", "school_type": "lac", "size_category": "small", "us_news_rank": 3, "acceptance_rate": 0.07, "sat_25": 1440, "sat_75": 1550, "tuition_oos": 60950, "avg_net_price": 22400, "intl_student_pct": 0.12, "student_faculty_ratio": 8.0, "graduation_rate_4yr": 0.86, "campus_setting": "suburban", "website_url": "https://www.swarthmore.edu"},
    {"name": "Pomona College", "name_cn": "波莫纳学院", "city": "Claremont", "state": "CA", "school_type": "lac", "size_category": "small", "us_news_rank": 4, "acceptance_rate": 0.07, "sat_25": 1440, "sat_75": 1550, "tuition_oos": 59518, "avg_net_price": 19200, "intl_student_pct": 0.11, "student_faculty_ratio": 7.0, "graduation_rate_4yr": 0.87, "campus_setting": "suburban", "website_url": "https://www.pomona.edu"},
    {"name": "Claremont McKenna College", "name_cn": "克莱蒙特麦肯纳学院", "city": "Claremont", "state": "CA", "school_type": "lac", "size_category": "small", "us_news_rank": 8, "acceptance_rate": 0.09, "sat_25": 1410, "sat_75": 1530, "tuition_oos": 62215, "avg_net_price": 24800, "intl_student_pct": 0.12, "student_faculty_ratio": 8.0, "graduation_rate_4yr": 0.85, "campus_setting": "suburban", "website_url": "https://www.cmc.edu"},
    {"name": "Bowdoin College", "name_cn": "鲍登学院", "city": "Brunswick", "state": "ME", "school_type": "lac", "size_category": "small", "us_news_rank": 6, "acceptance_rate": 0.09, "sat_25": 1400, "sat_75": 1530, "tuition_oos": 62340, "avg_net_price": 22500, "intl_student_pct": 0.08, "student_faculty_ratio": 9.0, "graduation_rate_4yr": 0.89, "campus_setting": "suburban", "website_url": "https://www.bowdoin.edu"},
    {"name": "Middlebury College", "name_cn": "明德学院", "city": "Middlebury", "state": "VT", "school_type": "lac", "size_category": "small", "us_news_rank": 9, "acceptance_rate": 0.13, "sat_25": 1370, "sat_75": 1520, "tuition_oos": 62070, "avg_net_price": 25600, "intl_student_pct": 0.12, "student_faculty_ratio": 8.0, "graduation_rate_4yr": 0.86, "campus_setting": "rural", "website_url": "https://www.middlebury.edu"},
    {"name": "Carleton College", "name_cn": "卡尔顿学院", "city": "Northfield", "state": "MN", "school_type": "lac", "size_category": "small", "us_news_rank": 6, "acceptance_rate": 0.16, "sat_25": 1400, "sat_75": 1540, "tuition_oos": 62046, "avg_net_price": 26200, "intl_student_pct": 0.10, "student_faculty_ratio": 9.0, "graduation_rate_4yr": 0.87, "campus_setting": "rural", "website_url": "https://www.carleton.edu"},
    {"name": "Grinnell College", "name_cn": "格林内尔学院", "city": "Grinnell", "state": "IA", "school_type": "lac", "size_category": "small", "us_news_rank": 14, "acceptance_rate": 0.11, "sat_25": 1370, "sat_75": 1520, "tuition_oos": 60464, "avg_net_price": 24200, "intl_student_pct": 0.18, "student_faculty_ratio": 8.0, "graduation_rate_4yr": 0.82, "campus_setting": "rural", "website_url": "https://www.grinnell.edu"},
    {"name": "Hamilton College", "name_cn": "汉密尔顿学院", "city": "Clinton", "state": "NY", "school_type": "lac", "size_category": "small", "us_news_rank": 14, "acceptance_rate": 0.12, "sat_25": 1380, "sat_75": 1520, "tuition_oos": 62070, "avg_net_price": 27400, "intl_student_pct": 0.09, "student_faculty_ratio": 9.0, "graduation_rate_4yr": 0.86, "campus_setting": "rural", "website_url": "https://www.hamilton.edu"},
    {"name": "Haverford College", "name_cn": "哈弗福德学院", "city": "Haverford", "state": "PA", "school_type": "lac", "size_category": "small", "us_news_rank": 16, "acceptance_rate": 0.14, "sat_25": 1380, "sat_75": 1520, "tuition_oos": 62850, "avg_net_price": 25800, "intl_student_pct": 0.10, "student_faculty_ratio": 8.0, "graduation_rate_4yr": 0.86, "campus_setting": "suburban", "website_url": "https://www.haverford.edu"},
    {"name": "Colby College", "name_cn": "科尔比学院", "city": "Waterville", "state": "ME", "school_type": "lac", "size_category": "small", "us_news_rank": 20, "acceptance_rate": 0.09, "sat_25": 1360, "sat_75": 1500, "tuition_oos": 63580, "avg_net_price": 23100, "intl_student_pct": 0.13, "student_faculty_ratio": 10.0, "graduation_rate_4yr": 0.85, "campus_setting": "rural", "website_url": "https://www.colby.edu"},
    {"name": "Bates College", "name_cn": "贝茨学院", "city": "Lewiston", "state": "ME", "school_type": "lac", "size_category": "small", "us_news_rank": 20, "acceptance_rate": 0.14, "sat_25": 1330, "sat_75": 1480, "tuition_oos": 62300, "avg_net_price": 26700, "intl_student_pct": 0.09, "student_faculty_ratio": 10.0, "graduation_rate_4yr": 0.85, "campus_setting": "suburban", "website_url": "https://www.bates.edu"},
    {"name": "Washington and Lee University", "name_cn": "华盛顿与李大学", "city": "Lexington", "state": "VA", "school_type": "lac", "size_category": "small", "us_news_rank": 11, "acceptance_rate": 0.17, "sat_25": 1370, "sat_75": 1500, "tuition_oos": 60660, "avg_net_price": 29200, "intl_student_pct": 0.05, "student_faculty_ratio": 8.0, "graduation_rate_4yr": 0.87, "campus_setting": "rural", "website_url": "https://www.wlu.edu"},
    {"name": "Colgate University", "name_cn": "科尔盖特大学", "city": "Hamilton", "state": "NY", "school_type": "lac", "size_category": "small", "us_news_rank": 18, "acceptance_rate": 0.12, "sat_25": 1360, "sat_75": 1500, "tuition_oos": 63910, "avg_net_price": 28300, "intl_student_pct": 0.08, "student_faculty_ratio": 9.0, "graduation_rate_4yr": 0.87, "campus_setting": "rural", "website_url": "https://www.colgate.edu"},
    {"name": "Harvey Mudd College", "name_cn": "哈维穆德学院", "city": "Claremont", "state": "CA", "school_type": "lac", "size_category": "small", "us_news_rank": 11, "acceptance_rate": 0.13, "sat_25": 1470, "sat_75": 1570, "tuition_oos": 62817, "avg_net_price": 30800, "intl_student_pct": 0.10, "student_faculty_ratio": 8.0, "graduation_rate_4yr": 0.82, "campus_setting": "suburban", "website_url": "https://www.hmc.edu"},
    {"name": "Davidson College", "name_cn": "戴维森学院", "city": "Davidson", "state": "NC", "school_type": "lac", "size_category": "small", "us_news_rank": 16, "acceptance_rate": 0.17, "sat_25": 1330, "sat_75": 1490, "tuition_oos": 58890, "avg_net_price": 25600, "intl_student_pct": 0.08, "student_faculty_ratio": 9.0, "graduation_rate_4yr": 0.88, "campus_setting": "suburban", "website_url": "https://www.davidson.edu"},
    {"name": "Wesleyan University", "name_cn": "卫斯理大学", "city": "Middletown", "state": "CT", "school_type": "lac", "size_category": "small", "us_news_rank": 18, "acceptance_rate": 0.14, "sat_25": 1370, "sat_75": 1520, "tuition_oos": 61244, "avg_net_price": 25800, "intl_student_pct": 0.12, "student_faculty_ratio": 8.0, "graduation_rate_4yr": 0.85, "campus_setting": "suburban", "website_url": "https://www.wesleyan.edu"},
    {"name": "Vassar College", "name_cn": "瓦萨学院", "city": "Poughkeepsie", "state": "NY", "school_type": "lac", "size_category": "small", "us_news_rank": 22, "acceptance_rate": 0.19, "sat_25": 1360, "sat_75": 1510, "tuition_oos": 63150, "avg_net_price": 26400, "intl_student_pct": 0.10, "student_faculty_ratio": 8.0, "graduation_rate_4yr": 0.85, "campus_setting": "suburban", "website_url": "https://www.vassar.edu"},
    {"name": "Smith College", "name_cn": "史密斯学院", "city": "Northampton", "state": "MA", "school_type": "lac", "size_category": "small", "us_news_rank": 14, "acceptance_rate": 0.21, "sat_25": 1330, "sat_75": 1500, "tuition_oos": 60050, "avg_net_price": 27200, "intl_student_pct": 0.14, "student_faculty_ratio": 9.0, "graduation_rate_4yr": 0.83, "campus_setting": "urban", "website_url": "https://www.smith.edu"},
    {"name": "Bryn Mawr College", "name_cn": "布林莫尔学院", "city": "Bryn Mawr", "state": "PA", "school_type": "lac", "size_category": "small", "us_news_rank": 30, "acceptance_rate": 0.31, "sat_25": 1280, "sat_75": 1470, "tuition_oos": 58740, "avg_net_price": 27500, "intl_student_pct": 0.22, "student_faculty_ratio": 8.0, "graduation_rate_4yr": 0.76, "campus_setting": "suburban", "website_url": "https://www.brynmawr.edu"},
    {"name": "Barnard College", "name_cn": "巴纳德学院", "city": "New York", "state": "NY", "school_type": "lac", "size_category": "small", "us_news_rank": 11, "acceptance_rate": 0.08, "sat_25": 1390, "sat_75": 1530, "tuition_oos": 63230, "avg_net_price": 27600, "intl_student_pct": 0.09, "student_faculty_ratio": 9.0, "graduation_rate_4yr": 0.84, "campus_setting": "urban", "website_url": "https://www.barnard.edu"},
    {"name": "Oberlin College", "name_cn": "欧柏林学院", "city": "Oberlin", "state": "OH", "school_type": "lac", "size_category": "small", "us_news_rank": 35, "acceptance_rate": 0.33, "sat_25": 1310, "sat_75": 1480, "tuition_oos": 61314, "avg_net_price": 30200, "intl_student_pct": 0.12, "student_faculty_ratio": 10.0, "graduation_rate_4yr": 0.74, "campus_setting": "rural", "website_url": "https://www.oberlin.edu"},
    {"name": "Macalester College", "name_cn": "玛卡莱斯特学院", "city": "Saint Paul", "state": "MN", "school_type": "lac", "size_category": "small", "us_news_rank": 26, "acceptance_rate": 0.27, "sat_25": 1310, "sat_75": 1480, "tuition_oos": 60928, "avg_net_price": 29800, "intl_student_pct": 0.15, "student_faculty_ratio": 10.0, "graduation_rate_4yr": 0.82, "campus_setting": "urban", "website_url": "https://www.macalester.edu"},
    {"name": "Scripps College", "name_cn": "斯克里普斯学院", "city": "Claremont", "state": "CA", "school_type": "lac", "size_category": "small", "us_news_rank": 30, "acceptance_rate": 0.29, "sat_25": 1330, "sat_75": 1490, "tuition_oos": 61950, "avg_net_price": 28200, "intl_student_pct": 0.08, "student_faculty_ratio": 9.0, "graduation_rate_4yr": 0.80, "campus_setting": "suburban", "website_url": "https://www.scrippscollege.edu"},
    {"name": "Bucknell University", "name_cn": "巴克内尔大学", "city": "Lewisburg", "state": "PA", "school_type": "lac", "size_category": "small", "us_news_rank": 35, "acceptance_rate": 0.34, "sat_25": 1240, "sat_75": 1410, "tuition_oos": 62424, "avg_net_price": 34500, "intl_student_pct": 0.07, "student_faculty_ratio": 9.0, "graduation_rate_4yr": 0.82, "campus_setting": "rural", "website_url": "https://www.bucknell.edu"},
    {"name": "Lafayette College", "name_cn": "拉法耶特学院", "city": "Easton", "state": "PA", "school_type": "lac", "size_category": "small", "us_news_rank": 38, "acceptance_rate": 0.30, "sat_25": 1260, "sat_75": 1420, "tuition_oos": 60930, "avg_net_price": 33200, "intl_student_pct": 0.09, "student_faculty_ratio": 10.0, "graduation_rate_4yr": 0.82, "campus_setting": "suburban", "website_url": "https://www.lafayette.edu"},
    {"name": "Kenyon College", "name_cn": "凯尼恩学院", "city": "Gambier", "state": "OH", "school_type": "lac", "size_category": "small", "us_news_rank": 30, "acceptance_rate": 0.30, "sat_25": 1280, "sat_75": 1440, "tuition_oos": 63580, "avg_net_price": 30200, "intl_student_pct": 0.07, "student_faculty_ratio": 10.0, "graduation_rate_4yr": 0.83, "campus_setting": "rural", "website_url": "https://www.kenyon.edu"},
    {"name": "Colorado College", "name_cn": "科罗拉多学院", "city": "Colorado Springs", "state": "CO", "school_type": "lac", "size_category": "small", "us_news_rank": 26, "acceptance_rate": 0.12, "sat_25": 1320, "sat_75": 1480, "tuition_oos": 63500, "avg_net_price": 27600, "intl_student_pct": 0.09, "student_faculty_ratio": 10.0, "graduation_rate_4yr": 0.83, "campus_setting": "urban", "website_url": "https://www.coloradocollege.edu"},
    {"name": "Mount Holyoke College", "name_cn": "曼荷莲学院", "city": "South Hadley", "state": "MA", "school_type": "lac", "size_category": "small", "us_news_rank": 38, "acceptance_rate": 0.34, "sat_25": 1260, "sat_75": 1440, "tuition_oos": 59000, "avg_net_price": 27800, "intl_student_pct": 0.24, "student_faculty_ratio": 10.0, "graduation_rate_4yr": 0.77, "campus_setting": "rural", "website_url": "https://www.mtholyoke.edu"},
    {"name": "Trinity College", "name_cn": "三一学院", "city": "Hartford", "state": "CT", "school_type": "lac", "size_category": "small", "us_news_rank": 46, "acceptance_rate": 0.30, "sat_25": 1210, "sat_75": 1400, "tuition_oos": 62540, "avg_net_price": 34200, "intl_student_pct": 0.10, "student_faculty_ratio": 9.0, "graduation_rate_4yr": 0.79, "campus_setting": "urban", "website_url": "https://www.trincoll.edu"},
    {"name": "Connecticut College", "name_cn": "康涅狄格学院", "city": "New London", "state": "CT", "school_type": "lac", "size_category": "small", "us_news_rank": 46, "acceptance_rate": 0.34, "sat_25": 1260, "sat_75": 1420, "tuition_oos": 61240, "avg_net_price": 32800, "intl_student_pct": 0.09, "student_faculty_ratio": 9.0, "graduation_rate_4yr": 0.80, "campus_setting": "suburban", "website_url": "https://www.conncoll.edu"},
    {"name": "Union College", "name_cn": "联合学院", "city": "Schenectady", "state": "NY", "school_type": "lac", "size_category": "small", "us_news_rank": 42, "acceptance_rate": 0.36, "sat_25": 1240, "sat_75": 1400, "tuition_oos": 62613, "avg_net_price": 35300, "intl_student_pct": 0.06, "student_faculty_ratio": 10.0, "graduation_rate_4yr": 0.80, "campus_setting": "urban", "website_url": "https://www.union.edu"},
    {"name": "Whitman College", "name_cn": "惠特曼学院", "city": "Walla Walla", "state": "WA", "school_type": "lac", "size_category": "small", "us_news_rank": 42, "acceptance_rate": 0.44, "sat_25": 1250, "sat_75": 1420, "tuition_oos": 57816, "avg_net_price": 31200, "intl_student_pct": 0.06, "student_faculty_ratio": 9.0, "graduation_rate_4yr": 0.80, "campus_setting": "rural", "website_url": "https://www.whitman.edu"},
    {"name": "Reed College", "name_cn": "里德学院", "city": "Portland", "state": "OR", "school_type": "lac", "size_category": "small", "us_news_rank": 38, "acceptance_rate": 0.42, "sat_25": 1320, "sat_75": 1500, "tuition_oos": 63530, "avg_net_price": 33400, "intl_student_pct": 0.07, "student_faculty_ratio": 10.0, "graduation_rate_4yr": 0.66, "campus_setting": "urban", "website_url": "https://www.reed.edu"},
]

COLUMNS = [
    "name", "name_cn", "city", "state", "school_type", "size_category",
    "us_news_rank", "acceptance_rate", "sat_25", "sat_75",
    "tuition_oos", "avg_net_price", "intl_student_pct",
    "student_faculty_ratio", "graduation_rate_4yr",
    "campus_setting", "website_url",
]


async def main():
    conn = await asyncpg.connect(DB_DSN)
    try:
        # 1. Get existing school names (case-insensitive)
        rows = await conn.fetch("SELECT LOWER(name) AS lname FROM schools")
        existing = {r["lname"] for r in rows}
        print(f"Existing schools in DB: {len(existing)}")

        # 2. Filter to only missing schools
        to_insert = [s for s in NEW_SCHOOLS if s["name"].lower() not in existing]
        skipped = len(NEW_SCHOOLS) - len(to_insert)
        print(f"Schools to insert: {len(to_insert)}  (skipped {skipped} already present)")

        if not to_insert:
            print("Nothing to do.")
            return

        # 3. Insert
        placeholders = ", ".join(f"${i+1}" for i in range(len(COLUMNS)))
        col_names = ", ".join(COLUMNS)
        sql = f"INSERT INTO schools (id, {col_names}) VALUES (gen_random_uuid(), {placeholders})"

        inserted = 0
        for school in to_insert:
            values = [school.get(c) for c in COLUMNS]
            await conn.execute(sql, *values)
            inserted += 1
            print(f"  + {school['name']}")

        print(f"\nDone. Inserted {inserted} schools.")

        # 4. Final count
        total = await conn.fetchval("SELECT count(*) FROM schools")
        print(f"Total schools now in DB: {total}")
    finally:
        await conn.close()


if __name__ == "__main__":
    asyncio.run(main())
